### PR TITLE
NBT (copied & adapted from https://github.com/Steveice10/OpenNBT)

### PR DESCRIPTION
**Pull request by RinesThaix**

### CODE REVIEW

**Review by JarvisCraft — CHANGES_REQUESTED** [review]
Use smaller copyright header by using our header + copyrights of the NBT APIs owners

**Comment by xxDark** [comment]
Do not close Input streams, since more data may be available

**Comment by RinesThaix** [comment]
> Do not close Input streams, since more data may be available

Ehm, streams are being closed only in internal methods that are being invoked in reading from file or from serialized byte array. What I'm trying to tell you is that all streams that this code closes are being instantiated also there, so there is no need in removing close() invocation.

Whether you are thinking of using try-finally or try-with-resources: I thought about this, but decided not to implement code that way, cause it brings us kind of overhead.

**Comment by RinesThaix** [comment]
> Use smaller copyright header by using our header + copyrights of the NBT APIs owners

I think it's better to use both licenses. Don't see anything against it.

**Review by JarvisCraft — APPROVED** [review]

**Pull request merged**
